baseURL = "https://casino.wstrm.dev/"
languageCode = "en-us"
title = "Docent Casino"
theme = "ananke"
publishDir = "docs"

[params]
	favicon = ""
	description = "The Docent Casino Club ™"
	#github = "https://github.com/wstrm/DocentCasino"
	background_color_class = "bg-black"
	featured_image = "/images/bond-casino.jpg"
